name: qqmusic
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  http: 0.12.0+2
  json_annotation: ^2.0.0
  flutter_swiper: ^1.1.6
  dio: ^3.0.1
  # dio: 2.1.16
  path_provider: ^1.2.0
  flutter_screenutil: ^0.6.0
  cached_network_image: ^1.1.1
  flutter_ijkplayer: ^0.3.3
  provider: ^3.1.0
  shared_preferences: ^0.5.3+4
  connectivity: ^0.4.4
  camera: ^0.5.5+1
  video_player: ^0.10.2+3
  sqflite: ^1.1.7+1
  flutter_easyrefresh: ^2.0.4
  flutter_spinkit: ^4.0.0
  pull_to_refresh: ^1.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_model: ^0.0.2
  build_runner: ^1.0.0
  json_serializable: ^2.0.0



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/p.jpg
    - assets/images/my_dynamic_color_skin_normal.png
    - assets/images/my_dynamic_color_skin_selected.png
    - assets/images/my_music_color_skin_normal.png
    - assets/images/my_music_color_skin_selected.png
    - assets/images/my_musichall_color_skin_normal.png
    - assets/images/my_musichall_color_skin_selected.png
    - assets/images/my_recommend_cale_color_skin_normal.png
    - assets/images/my_recommend_cale_color_skin_selected.png
    - assets/images/icon_menu_recognize_lyric.png
    - assets/images/label_search_icon.png
    - assets/images/fragment_my_music_more.png
    - assets/images/discovery_add_follow_light.png
    - assets/images/minibar_btn_playlist_highlight.png
    - assets/images/landscape_player_btn_pause_normal.png
    - assets/images/landscape_player_btn_play_normal.png
    - assets/images/live_gift_arrow_down.png
    - assets/images/maintabbar_button_more_normal_white.png

    - assets/images/lockscreen_player_btn_repeat_once_pressed.png
    - assets/images/lockscreen_player_btn_random_pressed.png
    
    - assets/images/player_background_real.png
    - assets/images/player_btn_close_normal.png
    - assets/images/player_btn_repeat_highlight.png
    - assets/images/lyric_play_pervious_click.png
    - assets/images/lyric_play_pervious_normal.png
    - assets/images/lyric_play_button_two_press.png
    - assets/images/lyric_pausebutton_hover.png
    - assets/images/lyric_play_next_click.png
    - assets/images/lyric_play_next_normal.png
    - assets/images/player_btn_playlist_highlight.png
    - assets/images/player_btn_favorite_highlight.png
    - assets/images/player_btn_favorited_highlight.png
    - assets/images/player_btn_download_highlight.png
    - assets/images/player_btn_share_normal.png
    - assets/images/player_btn_comment_short.png
    - assets/images/player_btn_comment_long.png
    - assets/images/player_btn_comment_normal.png
    - assets/images/player_btn_bz_hlight.png
    - assets/images/player_btn_dts_off.png
    - assets/images/player_btn_hq_hlight.png
    - assets/images/abc_scrubber_track_mtrl_alpha.9.png

    - assets/images/live_share_actionshet_normal.png
    - assets/images/album_folder_header_comment.png
    - assets/images/common_list_header_sort.png
    - assets/images/ringtone_play.png
    - assets/images/playlist_icon_download.png
    - assets/images/ic_download_list_download.png
    - assets/images/common_list_header_mutilchoose_not_follow_skin_highnight.png
    - assets/images/item_more_icon.png
    - assets/images/item_mv_icon.png
    - assets/images/playlist_icon_add_to.png
    - assets/images/playlist_icon_garbage.png
    - assets/images/playlist_icon_paper_clip.png
    - assets/images/playlist_icon_delete.png
    - assets/images/play_mode_normal.png
    - assets/images/play_mode_shuffle.png
    - assets/images/play_mode_single.png
    - assets/images/player_album_cover_default.png
    - assets/images/live_gift_arrow_right.png
    - assets/images/album_folder_header_like.png
    - assets/images/album_folder_header_comment.png
    - assets/images/album_folder_header_share.png
    - assets/images/profile_back_normal.png
    - assets/images/back_normal_white.png
    - assets/images/back_normal_black.png
    - assets/images/live_play_list_still.png
    - assets/images/lyric_playbutton_two.png
    - assets/images/minibar_btn_default_playlist.png
    - assets/images/minibar_btn_default_play.png
    - assets/images/btn_mv_landscape_play.png
    - assets/images/bg_qafp_recording.png
    - assets/images/bg_qafp_normal.png
    - assets/images/bg_qafp_clicked.png
    - assets/images/ic_qafp_6.png
    - assets/images/radio_live_entry_left_icon.png
    - assets/images/miniplayer_btn_radiolist_highlight.png
    - assets/images/icon_song_action_sheet_normal.png
    - assets/images/icon_song_action_sheet_up.png
    - assets/images/not_login_default_image.png

    - assets/media/ll.mp3
    - assets/media/2.mp4

  #  - images/a_dot_burr.jpeg 
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
